---
_target_: torchmoon.datamodules.deepcraterdata.CraterDataModule

data_dir: ${data_dir}
batch_size: 16
num_workers: 4
training_test_eval_split: [0.4, 0.4, 0.2]
download: true
pin_memory: false
image_size: 256